{
 "title": "kWh / Rate",
 "description": "Energy usage by time of day rate",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Energy Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Furnace",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsA0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Basement",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsA1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Network",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsA2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Dryer",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsA3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Fridge",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsB0" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Back Yard Panel",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsB1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Basement Freezer",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsB2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Second Floor Lights",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "ampsB3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*(10/3600)*120" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "kWh total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "alias": "kWh",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "kilowatts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*31/3600" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Peak",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 2 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT sum(\"kilowatts\") *10/3600 FROM \"160w\".\"voltage\" WHERE (\"rate\" = '0.132') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "kilowatts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*31/3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tou_rate", "operator": "=", "value": "0.132" }
     ]
    }
   ]
  },
  {
   "title": "Mid-Day",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 4 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT sum(\"kilowatts\") *10/3600 FROM \"160w\".\"voltage\" WHERE (\"rate\" = '0.132') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "kilowatts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*31/3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tou_rate", "operator": "=", "value": "0.094" }
     ]
    }
   ]
  },
  {
   "title": "Off Peak",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 6 },
   "format": "kwatth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT sum(\"kilowatts\") *10/3600 FROM \"160w\".\"voltage\" WHERE (\"rate\" = '0.132') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "kilowatts" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*31/3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "tou_rate", "operator": "=", "value": "0.065" }
     ]
    }
   ]
  },
  {
   "title": "kW (now)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 8 },
   "format": "kwatt",
   "valueName": "current",
   "targets": [
    {
     "alias": "kilowatts (now)",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "kilowatts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kilowatts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "kwatt", "label": "kilowatts" }
   ],
   "targets": [
    {
     "alias": "Kilowatts",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT distinct(\"kilowatts\") FROM \"160w\".\"voltage\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "kilowatts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "TOU Rate",
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "query": "SELECT distinct(\"rate\") *10 FROM \"160w\".\"voltage\" WHERE $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*10" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}